version: '3.8'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - gateway
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq_management
      ports: 
        - 25672:25672 # (erlang) communication between the nodes and CLI tool
        - 15672:15672 # communication with the web management API 
        - 5672:5672
      networks:
        - gateway
      environment:
        - RABBITMQ_DEFAULT_USER = admin
        - RABBITMQ_DEFAULT_PASS = passw123
      restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - ./esdata:/var/lib/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  gateway: {}
